// Shared helpers for the world generators (Worlds 7 to 9): a seeded PRNG, CSV writing,
// date arithmetic on plain numbers (no time zone surprises), and the case-file writer.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const root = join(dirname(fileURLToPath(import.meta.url)), "../..");

export function mulberry32(seed) {
  let a = seed;
  return function random() {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export const round = (n, places) => {
  const f = 10 ** places;
  return Math.round((n + Number.EPSILON) * f) / f;
};
export const pad = (n) => String(n).padStart(2, "0");

export const DAY = 86_400_000;
export const utc = (y, m, d, hh = 0, mm = 0, ss = 0) => Date.UTC(y, m - 1, d, hh, mm, ss);
export const dateStr = (ms) => {
  const d = new Date(ms);
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}`;
};
export const stampStr = (ms) => {
  const d = new Date(ms);
  return `${dateStr(ms)} ${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}`;
};

const csvCell = (v) => {
  const s = v === null || v === undefined ? "" : String(v);
  return /[",\n]/.test(s) || /^\s|\s$/.test(s) ? `"${s.replaceAll('"', '""')}"` : s;
};
export const toCsv = (cols, rows) =>
  [cols.join(","), ...rows.map((r) => cols.map((c) => csvCell(r[c])).join(","))].join("\n") +
  "\n";

export const hint = (columns) =>
  Object.fromEntries(
    Object.entries(columns).map(([name, [widthPx, numeric]]) => [
      name,
      { widthPx, numeric },
    ]),
  );

export const ANSWER_TAIL =
  "In Python, put your answer in df (df = ...); that table is what gets judged.\n\nIn SQL, create a NEW table named result that holds your answer: CREATE TABLE result AS SELECT ...; That table is what gets judged. You can run your query as often as you like; each run replaces the old result.";

export const sqlStarter = (intro, cols) =>
  `${intro}\n-- Your answer (columns: ${cols}) goes in a NEW table named result, like this:\n--   CREATE TABLE result AS SELECT ... ;\n-- Each run replaces the old result, so run as often as you like.\nSELECT * FROM data LIMIT 5;`;

/** Everything one world needs: seeded random helpers, data and case writers, roster. */
export function createWorld({ number, id, dir, seed, script, label }) {
  const random = mulberry32(seed);
  const dataDir = join(root, `apps/web/public/datasets/world-${number}`);
  const casesDir = join(root, `content/cases/${id}`);
  mkdirSync(dataDir, { recursive: true });
  mkdirSync(casesDir, { recursive: true });
  const license = {
    license: "CC0-1.0",
    provenance: `Synthetic — generated by scripts/${script} with a seeded deterministic PRNG. All names, ids, dates and amounts are invented.`,
  };
  const caseIds = [];
  const files = [];
  const kit = {
    random,
    pick: (list) => list[Math.floor(random() * list.length)],
    int: (lo, hi) => lo + Math.floor(random() * (hi - lo + 1)),
    chance: (p) => random() < p,
    shuffle(list) {
      const out = [...list];
      for (let i = out.length - 1; i > 0; i -= 1) {
        const j = Math.floor(random() * (i + 1));
        [out[i], out[j]] = [out[j], out[i]];
      }
      return out;
    },
    license,
    writeCsv(name, cols, rows, note) {
      writeFileSync(join(dataDir, name), toCsv(cols, rows));
      files.push(`- \`${name}\`: ${rows.length} rows, \`${cols.join(", ")}\`${note ? `; ${note}` : ""}.`);
      return `/datasets/world-${number}/${name}`;
    },
    writeCase(caseId, body) {
      caseIds.push(caseId);
      writeFileSync(
        join(casesDir, `${caseId}.json`),
        JSON.stringify({ id: caseId, world: id, ...body }, null, 2) + "\n",
      );
    },
    finish() {
      writeFileSync(
        join(root, `content/rosters/${id}.json`),
        JSON.stringify({ world: id, caseIds }, null, 2) + "\n",
      );
      writeFileSync(
        join(dataDir, "LICENSES.md"),
        `# World ${number} dataset licenses\n\nAll files are **CC0** (public domain dedication), synthetic, and generated by\n[\`scripts/${script}\`](../../../../scripts/${script}) with a seeded deterministic PRNG. Names,\nids, dates and amounts are invented. Regenerate with \`node scripts/${script}\`; the same script\nwrites the case files and their expected answers, so data and answer key cannot drift apart.\n\n${files.join("\n")}\n`,
      );
      console.log(`${label} written: ${caseIds.length} cases.`);
    },
  };
  return kit;
}
