import { describe, expect, it } from "vitest";
import { caseSchema } from "./case";

const validCase = {
  id: "tutorial-nulls",
  world: "boss-fights",
  datasetPath: "/datasets/world-1/tutorial-nulls.csv",
  datasetLicense: {
    license: "CC0-1.0",
    provenance: "Synthetic, generated by a seeded script.",
  },
  strings: {
    title: "The Null Hydra",
    briefing: "Every missing value regenerates the boss. Clear them all.",
  },
  starterCode: "df.isna().sum()",
  winCondition: {
    all: [{ predicate: "no_nulls", column: "email" }],
  },
};

describe("caseSchema", () => {
  it("accepts a valid case", () => {
    expect(caseSchema.safeParse(validCase).success).toBe(true);
  });

  it("accepts optional columnHints", () => {
    const result = caseSchema.safeParse({
      ...validCase,
      columnHints: { email: { widthPx: 180, numeric: false }, id: { numeric: true } },
    });
    expect(result.success).toBe(true);
  });

  it("rejects an id with invalid characters", () => {
    const result = caseSchema.safeParse({ ...validCase, id: "Tutorial Nulls!" });
    expect(result.success).toBe(false);
  });

  it("rejects a win condition with no predicates", () => {
    const result = caseSchema.safeParse({ ...validCase, winCondition: { all: [] } });
    expect(result.success).toBe(false);
  });

  it("rejects an unknown world", () => {
    const result = caseSchema.safeParse({ ...validCase, world: "the-underworld" });
    expect(result.success).toBe(false);
  });

  it("rejects a case missing datasetLicense", () => {
    const { datasetLicense: _unused, ...caseWithoutLicense } = validCase;
    const result = caseSchema.safeParse(caseWithoutLicense);
    expect(result.success).toBe(false);
  });

  it("rejects a case missing starterCode", () => {
    const { starterCode: _unused, ...caseWithoutStarter } = validCase;
    const result = caseSchema.safeParse(caseWithoutStarter);
    expect(result.success).toBe(false);
  });
});
